### ISSUE TITLE
switch from region to memmap?

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/wasmtime#10]
#9 proposes ading a dependency on memmap, so we should consider using memmap rather than region for executable memory too.

**Comment by pepyakin** [comment]
Yeah, I thought about that, by the `memmap` API conflates this: [`map_exec`](https://docs.rs/memmap/0.6.2/memmap/struct.MmapOptions.html#method.map_exec) takes `File` parameter. In our case we want anonymous mapping.

**Comment by sunfishcode** [comment]
That's ok. We don't want the memory to be executable until after we write to it. We allocate normal anonymous pages and set the protection when they're ready.

**Comment by pepyakin** [comment]
Hm, and for that we would need `region` since `memmap` doesn't have such APIs, don't we?

**Comment by sunfishcode** [comment]
Could [`make_read_only`](https://docs.rs/memmap/0.6.2/memmap/struct.MmapMut.html#method.make_read_only) and [`make_exec`](https://docs.rs/memmap/0.6.2/memmap/struct.MmapMut.html#method.make_exec) do it? It's a little unfortunate that there doesn't seem to be a way to do both at the same time though.

**Comment by pepyakin** [comment]
oh, sorry, didn't know about those!

**Comment by sunfishcode** [comment]
Actually, it looks like make_exec should be sufficient to also make the memory read-only.

**Comment by sunfishcode** [comment]
A complicating factor with memmap is that it doesn't naturally support allocations consisting of some writeable pages and non-non-writeable pages. And other than this specialized need, we don't need a lot of other features, so I decided to just [implement mmap support directly](https://github.com/CraneStation/wasmtime/blob/master/lib/execute/src/mmap.rs) for now.
