### ISSUE TITLE
What is the goal of this project?

### ISSUE THREAD

**Issue by pepyakin** [CraneStation/wasmtime#11]
What does the description means?

"Standalone JIT-style runtime support for WebAsssembly code in Cranelift"

Can I use this project as substitute for `wasmi`? Like instantiate a module providing imports (satisfied by other modules and/or host functions), and execute exports.

Or is it for running wasm executables (something like [cervus](https://github.com/cervus-v/cervus))?

**Comment by sunfishcode** [comment]
It's still evolving :-). I think it's useful to have a simple runner program for executables, but ideally the libraries should be usable in other applications as well.

**Comment by pepyakin** [comment]
Thanks
