### ISSUE TITLE
unable to give explicit import module with wasi-sdk

### ISSUE THREAD

**Issue by gnanasekar-somanathan** [CraneStation/wasmtime#110]
Hi, have a simple c program
test.c like below

#define TEST_IMPORT __attribute__((__import_module__("foo"), __import_name__("bar")))
int __bar() TEST_IMPORT __attribute__((__warn_unused_result__));
int main(int argc, char** argv) {
    __bar();
    return 0;
}

When wasi-sdk Clang test.c get below error
wasm-ld: error: /tmp/application-c6fef0.o: undefined symbol: __bar

Shouldn't it generate a wasm module which has following import
(import "foo" "bar" (func $bar (result i32)))
Assuming foo module is implemented intrinsically in wasmtime.

**Comment by kubkon** [comment]
Correct me if I'm wrong, but it sounds like you want [dynamic linking](https://webassembly.org/docs/dynamic-linking/), and, as far as I am aware, it's not implemented yet [wasi-sysroot/dlopen.c](https://github.com/CraneStation/wasi-sysroot/blob/320054e84f8f2440def3b1c8700cedb8fd697bf8/libc-top-half/musl/src/ldso/dlopen.c).

Perhaps @sunfishcode or @pchickey could shed some more light/offer some guidance on this?

**Comment by gnanasekar-somanathan** [comment]
Yes, kind of dynamic linking. I m interested in adding my own custom interface similar to wasi_unstable module of wasi.

**Comment by pchickey** [comment]
I believe you just need to pass the linker the `--allow-undefined` flag to make this work: 
```
# /opt/wasi-sdk/bin/clang test.c -o test.wasm -Wl,--allow-undefined
test.c:4:2: warning: ignoring return value of function declared with 'warn_unused_result'
      attribute [-Wunused-result]
        __bar();
        ^~~~~
1 warning generated.
# wasm2wat test.wasm
(module
  (type (;0;) (func (param i32 i32) (result i32)))
  (type (;1;) (func (param i32 i32 i32) (result i32)))
  (type (;2;) (func (result i32)))
  (type (;3;) (func (param i32)))
  (type (;4;) (func))
  (type (;5;) (func (param i32) (result i32)))
  (import "wasi_unstable" "fd_prestat_get" (func $__wasi_fd_prestat_get (type 0)))
  (import "wasi_unstable" "fd_prestat_dir_name" (func $__wasi_fd_prestat_dir_name (type 1)))
  (import "wasi_unstable" "environ_sizes_get" (func $__wasi_environ_sizes_get (type 0)))
  (import "wasi_unstable" "environ_get" (func $__wasi_environ_get (type 0)))
  (import "wasi_unstable" "args_sizes_get" (func $__wasi_args_sizes_get (type 0)))
  (import "wasi_unstable" "args_get" (func $__wasi_args_get (type 0)))
  (import "foo" "bar" (func $__bar (type 2)))
  (import "wasi_unstable" "proc_exit" (func $__wasi_proc_exit (type 3)))
  (import "wasi_unstable" "fd_fdstat_get" (func $__wasi_fd_fdstat_get (type 0)))
  (func $__wasm_call_ctors (type 4))
  (func $_start (type 4)
    (local i32 i32 i32 i32)
    get_global 0
...
```

**Comment by kubkon** [comment]
I stand corrected then. Nice one, thanks for the clarification! :+1:

**Comment by gnanasekar-somanathan** [comment]
Thanks @kubkon @pchickey. I can see the import now.
