### ISSUE TITLE
Implementing `mkdir -p`

### ISSUE THREAD

**Issue by willemneal** [CraneStation/wasmtime#124]
I'm implementing Wasi for AssemblyScript and currently I'm confused with the API for creating a directory.  Is it safe to assume that by default trying to create a directory, whose parent(s) don't exist that it would fail? 

Also what is the best way to determine if a file or directory exists?

**Comment by sunfishcode** [comment]
Yes, `__wasi_path_create_directory` only creates one directory, similar to POSIX `mkdir`, and fails if the parent doesn't exist.

The typical way to test whether a file or directory exists is to just try to do whatever you would want to do, and handle errors in case it doesn't work. For `mkdir -p`, this means that you can just call `__wasi_path_create_directory` once for each path component. At each component, if you get `__WASI_EEXIST`, then it already exists and you can move the the next component. If it succeeds, then you just created it and you can move to the next component.

**Comment by willemneal** [comment]
Thanks! That makes a lot of sense.

**Comment by tschneidereit** [comment]
Closing this based on @sunfishcode's comment.
