### ISSUE TITLE
Meta: pass the testsuite

### ISSUE THREAD

**Issue by pepyakin** [CraneStation/wasmtime#14]
This will require at least these features:

- API for reading value of instance globals
- API for executing exported functions on the instance. This includes:
    - passing arguments and receiving result value in case of successful execution (#17)
- `call_indirect` implementation (signature checking, checking the item isn't null, etc)
- jump tables (#16)
- proper instantiation that allows importing external functions
- a way of defining host functions that can access embedder defined state

**Comment by sunfishcode** [comment]
All of the above are now implemented on master. The spec testsuite now passes!

**Comment by pepyakin** [comment]
That’s just awesome! Great job!
