### ISSUE TITLE
Newbie Question: does wasmtime support http requests?

### ISSUE THREAD

**Issue by andykais** [CraneStation/wasmtime#163]
Hi all, I am fairly new to learning webassembly. I have used it in the browser, and understand that I can wrap js functions around the `fetch` api to make http requests, but running wasm in nodejs, or as a standalone with wasmtime, is it possible to make http requests?

**Comment by sunfishcode** [comment]
It is not currently possible to make http requests from Wasmtime. However, networking functionality, likely including http, is something we're expecting to add in [WASI](https://github.com/WebAssembly/WASI) in the future, and implement in Wasmtime.
