### ISSUE TITLE
Use `try_from`

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/wasmtime#169]
As of Rust 1.34, the new [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) interfaces are stable in the standard library. We should use these in place of the `cast` crate where applicable.

For examples of how to do this, see [the corresponding PR in Cranelift](https://github.com/CraneStation/cranelift/pull/785), although note that Wasmtime uses `cast` much more extensively.

**Comment by kubkon** [comment]
That's a great idea, so I'll +1 this!
