### ISSUE TITLE
test-all.sh failing - requires cargo-fmt

### ISSUE THREAD

**Issue by frehberg** [CraneStation/wasmtime#24]
I did an update today, (head 74ccddcd64bdb1bbfd17f92272fedb35750346b2)

when I try to execute ./test-all.sh the script fails to to missing tool cargo-fmt.
Seems my setup of rustup is too old (rustup 1.14.0 (1e51b07cc 2018-10-04))

```
======  Rust formatting  ======
error: toolchain 'stable-x86_64-unknown-linux-gnu' does not have the binary `cargo-fmt`
Formatting diffs detected! Run "cargo fmt --all" to correct.
```

Solution: Installing the tool cargo-fmt explicitly for stable or nightly setup did solve the issue

```
rustup component add rustfmt-preview
```

Maybe the script should ask the user to update "rustup"

**Comment by sunfishcode** [comment]
Thanks for the report! The script has code to recommend that rustup comand, but it was testing for the existence of rustfmt rather than on cargo fmt working. Can you test whether #25 works for you?
