### ISSUE TITLE
fd_write should be unbuffered

### ISSUE THREAD

**Issue by kanaka** [CraneStation/wasmtime#255]
fd_write should be unbuffered to match the behavior of writev. Buffering can be implemented in the application if desired, however, fd_write being buffered means there is no way to do unbuffered writes (there is no WASI flush API call and there shouldn't be at this level). This is using the dev release of wasmtime from today (95bcc63). This is a regression from a a few months ago. Note that recent builds of wasmer and lucet have unbuffered fd_write.

Here is a simple test case that should print a prompt, read a string and echo it:

```
(module
  (import "wasi_unstable" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_unstable" "fd_read" (func $fd_read (param i32 i32 i32 i32) (result i32)))

  (memory 10)
  (export "memory" (memory 0))

  (func $main (local i32)
    (i32.store offset=0 (i32.const 4) (i32.const 12))  ;; iovec ptr
    (i32.store offset=4 (i32.const 4) (i32.const 2))   ;; iovec len
    (i32.store offset=0 (i32.const 12) (i32.const 62)) ;; string '> '
    (i32.store offset=1 (i32.const 12) (i32.const 32))
    (i32.store offset=2 (i32.const 12) (i32.const 0))
    ;; print prompt
    (drop (call $fd_write (i32.const 1) (i32.const 4) (i32.const 1) (i32.const 256)))

    (i32.store offset=0 (i32.const 16) (i32.const 24))  ;; iovec ptr
    (i32.store offset=4 (i32.const 16) (i32.const 200)) ;; iovec len
    ;; read
    (drop (call $fd_read (i32.const 0) (i32.const 16) (i32.const 1) (i32.const 256)))
    ;; echo
    (drop (call $fd_write (i32.const 1) (i32.const 16) (i32.const 1) (i32.const 256)))
  )

  ;;(start $main)
  (export "_start" $main)
)
```

And here is the behavior:

```
$ wasm-as wasitests/echo2.wat -o wasitests/echo2.wasm
$ wasmtime wasitests/echo2.wasm
typed by the user
> typed by the user
```

The correct behavior should be:

```
$ wasmtime wasitests/echo2.wasm
> typed by the user
typed by the user
```

**Comment by kubkon** [comment]
Hi! Thanks for filing the issue. We've recently changed the implementation of `fd_write` and `fd_read` and this must have sneaked it. I'll have a look and let you know when I have a draft of a fix :-)

**Comment by kubkon** [comment]
@kanaka it should be fixed now. Could you double check against the latest upstream and confirm that it works fine for you?

**Comment by kanaka** [comment]
I rebuilt wasmtime and didn't get the fix. Then realized it's in a module. I tried updating the version of wasi-common in Cargo.toml and got the following link time errors:

```
...
/mal/wasmtime/target/release/deps/libwasi_common-24c49d090c9bb950.rlib(wasi_common-24c49d090c9bb950.wasi_common.2pbfosmq-cgu.6.rcgu.o):wasi_common.2pbfosmq-cgu.6:(.text.wasi_common_random_get+0x0): first defined here
          /mal/wasmtime/target/release/deps/libwasi_common-8b3e6efcaec3722c.rlib(wasi_common-8b3e6efcaec3722c.wasi_common.3sry3gv5-cgu.15.rcgu.o): In function `wasi_common_sched_yield':
          wasi_common.3sry3gv5-cgu.15:(.text.wasi_common_sched_yield+0x0): multiple definition of `wasi_common_sched_yield'
          /mal/wasmtime/target/release/deps/libwasi_common-24c49d090c9bb950.rlib(wasi_common-24c49d090c9bb950.wasi_common.2pbfosmq-cgu.6.rcgu.o):wasi_common.2pbfosmq-cgu.6:(.text.wasi_common_sched_yield+0x0): first defined here
```

Can you give me a hint about how I should build this?

**Comment by kubkon** [comment]
Ahhh, apologies for that! It seems that `wasi-common` was not updated to the latest rev in upstream. I've bumped the rev and so it should be fine now if you build upstream directly.

In terms of the error, it looks to me like you've updated the version of `wasi-common` in only one crate being [wasmtime-wasi](https://github.com/CraneStation/wasmtime/blob/master/wasmtime-wasi/Cargo.toml) but it also needs to be updated in the Wasmtime crate's root as well [Cargo.toml](https://github.com/CraneStation/wasmtime/blob/master/Cargo.toml). :-)

**Comment by kanaka** [comment]
I pulled down the nightly CI build and can confirm that it is now fixed.
