### ISSUE TITLE
wasmjit blog post links are 404

### ISSUE THREAD

**Issue by vitiral** [CraneStation/wasmtime#269]
https://www.wasmjit.org/blog/spectre-mitigations-part-1.html
https://www.wasmjit.org/blog/spectre-mitigations-part-2.html

I cannot find new links via google. I'm not sure if they exist.

**Comment by sunfishcode** [comment]
Ah, thanks for pointing that out. I've now opened https://github.com/CraneStation/wasmtime/pull/277 to remove them for now.

**Comment by sunfishcode** [comment]
Fixed in #277!
