### ISSUE TITLE
Compiling on OpenBSD 6.6

### ISSUE THREAD

**Issue by jesselucas** [CraneStation/wasmtime#333]
On OpenBSD 6.6 `cargo build --release` fails with the following error:

```
error[E0425]: cannot find function `get_region` in module `os`
   --> /home/j/.cargo/registry/src/github.com-1ecc6299db9ec823/region-2.1.2/src/lib.rs:133:7
    |
133 |   os::get_region(page::floor(address as usize) as *const u8)
    |       ^^^^^^^^^^ not found in `os`
```

**Comment by bjorn3** [comment]
You should probably open an issue at https://github.com/darfink/region-rs, as that is the crate which fails to compile on OpenBSD.

**Comment by jesselucas** [comment]
Thank you! I opened [an issue](https://github.com/darfink/region-rs/issues/8) with the [region-rs](https://github.com/darfink/region-rs) crate.
