### ISSUE TITLE
Why would I use this in the browser?

### ISSUE THREAD

**Issue by carlsmith** [CraneStation/wasmtime#359]
I saw that you have a polyfill for the Web and was perplexed by it.

As I (mis)understand WebAssembly, it does not actually implement a functional VM with an API for using it, but really implements all of the parts for a VM with an API for combining them to build the VM you need for your application. The host is responsible for the environment, initializing everything, resolving imports, memory mapping et cetera, so every WASM VM is host dependent and intrinsically non-standard.

Do you intend for WASI to be implemented in browsers as a standard that can also be implemented natively for people that want to use WebAssembly to run browser code outside the browser? I don't get it. C and Rust already run natively, on sandboxed VMs is we want them. Isn't this beyond scope for a Web standards group? I'm lost. Sorry.

Who will use WASI, and where?

**Comment by tschneidereit** [comment]
(Note: this is the repo for Wasmtime, a runtime implementing WASI, not WASI itself.)

> The host is responsible for the environment, initializing everything, resolving imports, memory mapping et cetera, so every WASM VM is host dependent and intrinsically non-standard.

You're right that the way all this is implemented can vary significantly between hosts. However, that doesn't mean that the behavior exposed to WebAssembly code can't be standardized, just as the fact that, e.g., JavaScript engines have significant differences in their implementation strategies doesn't mean that they can't all implement the EcmaScript standard.

> Do you intend for WASI to be implemented in browsers as a standard that can also be implemented natively for people that want to use WebAssembly to run browser code outside the browser?

It's more the other way around: WASI won't be natively implemented in browsers for at least quite a while, whereas there already are multiple native implementations outside the browser, such as Wasmtime. You're right that languages targeting WASI can already run outside the browser, but there are a whole bunch of scenarios in which you wouldn't want to just run native applications compiled from them without any additional care, with portability and security being the main reasons.

The [WASI homepage](https://wasi.dev/) has links to further information, but in particular the [initial announcement](https://hacks.mozilla.org/2019/03/standardizing-wasi-a-webassembly-system-interface/) contains some answers to your questions.

I'll close this issue, as it's not really about Wasmtime, but I hope the information above is helpful.
