### ISSUE TITLE
Build Failure on wasmtime-execute v0.0.0

### ISSUE THREAD

**Issue by jlb6740** [CraneStation/wasmtime#37]
Hi ... I just did a new checkout. My head is at a6358614257. I am building with "cargo build" but this produces an error. I am running Linux mint 18.1 which is compatible with Ubuntu 16.04

   Compiling docopt v1.0.2                                                                                                                          
   Compiling faerie v0.6.0                                                                                                                          
   Compiling wasmtime-execute v0.0.0 (/home/jlbirch/wasmtime2/lib/execute)                                                                          
error: failed to run custom build command for `wasmtime-execute v0.0.0 (/home/jlbirch/wasmtime2/lib/execute)`                                       
process didn't exit successfully: `/home/jlbirch/wasmtime2/target/debug/build/wasmtime-execute-2cff1c1b05e773fc/build-script-build` (exit code: 101)
--- stdout

Any suggestions?

**Comment by sunfishcode** [comment]
Oh, this might require cmake to be installed, as we have some C++ files to support signal handling.

**Comment by jlb6740** [comment]
My cmake is at 3.5.1:

yshou-mint:~/wasmtime2$ cmake --version
cmake version 3.5.1

Any version in particular? Usually when cmak is the issue it warms about a particular version or is not found but in this case I see neither error.

**Comment by sunfishcode** [comment]
Do you also have clang installed? That's needed to compile the C++ files.

**Comment by sunfishcode** [comment]
Does `cargo build --verbose` say anything useful?

**Comment by jlb6740** [comment]
Ahh ... I'm sorry. I see, thanks for the pointer. I have clang installed, but looks like it needs libclang. I would of thought the two were a package deal but guess not. Let me figure out how to install libclang and see how it is related to the clang I already have available.

**Comment by jlb6740** [comment]
It has built now. Also had to add stdbool.h to my path and then also switch from the stable toolchain of rust to the nightly. The run_wast did not execute as expected my call.wast example as expected but that is a separate question. I'll close this issue now.
