### ISSUE TITLE
Lightbeam feature build errors

### ISSUE THREAD

**Issue by jlb6740** [CraneStation/wasmtime#389]
The Lightbeam codegen feature is not building: 

> cargo build --features lightbeam

Is this the proper way to build? I went back several weeks and could not find a build where the build succeeded. 

Build error: 
![image](https://user-images.githubusercontent.com/45402135/65805162-58295500-e139-11e9-9646-bd8b7e64fa0c.png)

I was looking into the build to compare the aot (wasm2obj) and jitted code.

**Comment by jlb6740** [comment]
How is it expected that lightbeam is be dependent on cranelift. I would like to resolve build errors with enabling the feature in wasmtime but am noticing errors about SigType and Signature traits for lightbeam not being implemented in cranelift_codegen::ir:: w.r.t. the ModuleContext trait. Not understanding the dependency between lightbeam and cranelift I am not sure if it makes sense to attempt to  implement what rust is asking for or if the ModuleContext trait implementation needs to be modified?

**Comment by bjorn3** [comment]
Updating the cranelift version lightbeam depends on (https://github.com/CraneStation/lightbeam/blob/bbd7e91d1c524b7d7f5b88c4e89cffe03c70b3ef/Cargo.toml#L22), may fix the error.

**Comment by jlb6740** [comment]
@bjorn3 Thanks for the suggestion. Yes, switching to .44 removed got rid of those errors but revealed another related to reloc_constant. 

![image](https://user-images.githubusercontent.com/45402135/65905014-965e8880-e374-11e9-9acd-61b187aca1b2.png)

But I'll look into that now. 

Thanks.

**Comment by jlb6740** [comment]
jlb6740:update_cranelift_cg_ver_44
