### ISSUE TITLE
V128 support removed

### ISSUE THREAD

**Issue by abrown** [CraneStation/wasmtime#441]
@alexcrichton, I was working on #388 and when I rebased I noticed that #434 introduces an issue with the SIMD implementation in `wasmtime`. Previously, there was a way to convert a `V128Const` to a `RuntimeValue` (see `runtime_value` in `wasmtime-wast/src/wast.rs`). #434 removed this functionality.

To re-add this, I propose we add a method on the new `V128Const` enum in `wat` (see `crates/wast/src/ast/expr.rs`) such as `to_le_bytes` that returns a `[u8; 16]` that can be owned by `RuntimeValue::V128`. What do you think?

**Comment by alexcrichton** [comment]
Oh dear sorry about that! I remove that support before I realized wasmtime had more SIMD support than I thought, and after going back and adding support I forgot to go and update this branch to handle `v128.const` instructions. Your proposal sounds great to me and I'll work on adding that in!

**Comment by alexcrichton** [comment]
Ok PR sent in https://github.com/CraneStation/wasmtime/pull/442
