### ISSUE TITLE
Lightbeam build broken with introduction of ModuleTranslateState

### ISSUE THREAD

**Issue by jlb6740** [CraneStation/wasmtime#446]
cargo build --features=lightbeam

> error[E0412]: cannot find type `ModuleTranslationState` in this scope
>   --> wasmtime-environ/src/lightbeam.rs:23:30
>    |
> 23 |         module_translation: &ModuleTranslationState,
>    |                              ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
> help: possible candidate is found in another module, you can import it into scope
>    |
> 3  | use cranelift_wasm::ModuleTranslationState;
>    |

**Comment by jlb6740** [comment]
Fix is issued here: jlb6740:fix-lightbeam-build-support-for-module-translate-state

**Comment by sunfishcode** [comment]
Fix merged, thanks!
