### ISSUE TITLE
CI failing for cargo doc (wasmtime-debug) but is not reproduced locally.

### ISSUE THREAD

**Issue by jlb6740** [CraneStation/wasmtime#491]
https://github.com/CraneStation/wasmtime/pull/360/checks?check_run_id=291613386

CI fails for cargo doc as seen in the link above. The pull request in question does not modify the files that are at the source of the failures (wasmtime-debug/src/lib.rs)
I've tried to reproduce this failure with cargo version 1.38.0-nightly and 1.40-0-nightly but I am not able to reproduce the error with either version. Is something wrong with CI? How can I tell which version of cargo is being run?

**Comment by bjorn3** [comment]
faerie released a patch version which updates the public dep target-lexicon. This is a semver incompatible change. You couldnt reproduce locally, as your Cargo.lock contains an older version.

**Comment by peterhuene** [comment]
That's correct.  @sunfishcode is working on taking a new cranelift release to address this.

**Comment by sunfishcode** [comment]
Cranelift 0.49 is now published, which uses faerie 0.12.0, which should hopefully correct this.

**Comment by jlb6740** [comment]
https://github.com/CraneStation/wasmtime/pull/499
:+1:
