### ISSUE TITLE
WASI: vague description of __wasi_random_get()

### ISSUE THREAD

**Issue by npmccallum** [CraneStation/wasmtime#72]
1. Does this API intend to provide random data suitable for use in cryptography?
2. Does this API block if the system currently cannot provide sufficient entropy or does it return degraded randomness?

**Comment by sunfishcode** [comment]
Good questions :-).

`random_get` is roughly meant to align with `getentropy`, which is non-standard, but available on a variety of systems. It returns "high-quality" random data, in the sense that `getentropy` man pages intend that phrase. 

And, it can block, as `getentropy` can. I've now added a sentence to the documentation mentioning that.

That said, I can easily believe there's room for improvement here :-).

**Comment by sunfishcode** [comment]
The API has been updated to answer these questions!
