### ISSUE TITLE
"Steps for usage" wasmtime link update

### ISSUE THREAD

**Issue by holygits** [CraneStation/wasmtime#77]
Instructions [here](https://github.com/alexcrichton/rust/releases/tag/wasi3) need to be updated to use this wasmtime repo, not the archived one.

**Comment by bnjbvr** [comment]
@alexcrichton Would it make sense to update the step 7 instruction here?

**Comment by alexcrichton** [comment]
Oops, updated!

**Comment by sunfishcode** [comment]
Thanks all!
