### ISSUE TITLE
cannot find stddef.h

### ISSUE THREAD

**Issue by mcculley** [CraneStation/wasmtime#80]
When I execute `cargo build`, I get
`./sandboxed-system-primitives/include/wasmtime_ssp.h:13:10: fatal error: 'stddef.h' file not found`

I am using rustc version 1.35.0-nightly.

**Comment by sunfishcode** [comment]
What platform are you building on?

**Comment by mcculley** [comment]
I am on Ubuntu. I just reinstalled clang after uninstalling it and it works. Maybe the documentation should be more explicit about the versions of clang and clang-dev that are necessary. This is likely just user error on my part.

**Comment by sunfishcode** [comment]
Yes, I agree we should document the build requirements. I don't believe clang-dev is necessary; it should just be clang, via the bindgen dependency, and cmake. Did you need to install any other packages?

**Comment by mcculley** [comment]
I needed to install cmake and cargo.

**Comment by Lyberta** [comment]
Hit the same error while building with GCC 8.3.0. This is totally undocumented.

**Comment by sunfishcode** [comment]
I've now created https://github.com/CraneStation/wasmtime/pull/94; does installing clang and cmake fix the issue here?

**Comment by Lyberta** [comment]
Yes, but what's the minimum required version of Clang?

**Comment by sunfishcode** [comment]
I've now added a link [to bindgen's documentation](https://github.com/rust-lang/rust-bindgen/blob/master/book/src/requirements.md) on the required clang version, and installation instructions.

**Comment by Lyberta** [comment]
Ok, good.

**Comment by sunfishcode** [comment]
I believe this is fixed now, as the build requirements are now documented.

**Comment by caiyesd** [comment]
I still meet this issue with clang3.9. And cmake, llvm, cargo are also all installed.

./sandboxed-system-primitives/include/wasmtime_ssp.h:13:10: fatal error: 'stddef.h' file not found
./sandboxed-system-primitives/include/wasmtime_ssp.h:13:10: fatal error: 'stddef.h' file not found, err: true

**Comment by caiyesd** [comment]
My temporary solution is to add the `include` path to `wasmtime-wasi-c/build.rs`.

diff --git a/wasmtime-wasi-c/build.rs b/wasmtime-wasi-c/build.rs
index ed070ea..e8e7cd3 100644
--- a/wasmtime-wasi-c/build.rs
+++ b/wasmtime-wasi-c/build.rs
@@ -14,6 +14,7 @@ fn main() {
     let bindings_builder = bindgen::Builder::default()
         .header("sandboxed-system-primitives/include/wasmtime_ssp.h")
         .header("sandboxed-system-primitives/src/posix.h")
+        .clang_arg("-I/usr/include/clang/3.9/include")
         .whitelist_function("wasmtime_ssp_.*")
         .whitelist_function("fd_table_init")
         .whitelist_function("fd_table_insert_existing")

**Comment by sunfishcode** [comment]
If you put this in a file named test.c:
```c
#include <stddef.h>
```
and run `clang -c test.c`, do you get an error?

**Comment by sunfishcode** [comment]
Is there a package like libclang-common-6.0-dev that you can install? If so, and if that fixes it, we may need to add that to the documentation too.

It also happens that we're getting really close to be able to enable the new wasi-common implementation, which is entirely written in Rust, at which point we can disable wasmtime-wasi-c (at least by default).
