### ISSUE TITLE
__wasi_random_get in wasi polyfill not defined

### ISSUE THREAD

**Issue by nipzu** [CraneStation/wasmtime#89]
The javascript polyflll function `random_get` calls an undefined function `__wasm_random_get` and gives an error. Calling the `___wasi_random_get` function with 3 underscores would generate a random number without errors. Most of the other WASI functions seem to have 3 underscores so why doesn't this function have them? The `sched_yield` and `sock_shutdown` functions also seem to be calling undefined functions.
https://github.com/CraneStation/wasmtime/blob/a6f31a2be331f66a26e5516cae80c02261b49744/wasmtime-wasi/js-polyfill/wasi.js#L455

**Comment by zhuowei** [comment]
@sunfishcode  I can still reproduce this on the [publicly hosted polyfill](https://wasi.dev/polyfill/); you might want to update the polyfill on the site.

**Comment by sunfishcode** [comment]
It's now updated with this fix.
