### ISSUE TITLE
Missing Cargo.toml after lightbeam commit

### ISSUE THREAD

**Issue by moderation** [CraneStation/wasmtime#96]
Since the introduction of Lightbeam with https://github.com/CraneStation/wasmtime/commit/9bf6d73210aab3665102381377a8ffa6ff1445ec both `cargo update` and cargo build --release` result in the following error.

```
error: failed to read `/wasmtime/rust/wasmtime/lightbeam/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

**Comment by pepyakin** [comment]
Have you tried to update submodules?

**Comment by moderation** [comment]
Thanks. `git clone --recurse-submodules https://github.com/CraneStation/wasmtime.git` worked. I'm pretty sure did a standard clone with `git clone https://github.com/CraneStation/wasmtime.git` prior to the lightbeam commit. Working now. Will see if there is a docs change I can make that might help.

**Comment by xuqzab** [comment]
Readme needs to be updated to include using git clone --recurse-submodules https://github.com/CraneStation/wasmtime.git.  Plain old git clone still doesn't work and no mention of correct command in readme.

**Comment by sunfishcode** [comment]
I've now filed https://github.com/CraneStation/wasmtime/pull/103 to add this step to the README.
